require 'rubygems'
require 'airake'

ENV["AIRAKE_ROOT"] = File.dirname(__FILE__)

task :default => "flash:compile" do; end
task :compile => "flash:compile" do; end
task :clean => "flash:clean" do; end